### ISSUE TITLE
equal to

### ISSUE THREAD

**Issue by eknowles** [Turistforeningen/node-mongo-querystring#13]
Currently there isn't a way to use $gte. Need to find a url save symbol for equal.

**Comment by Starefossen** [comment]
I think `?foo=<=10` should be URL safe.

**Comment by Starefossen** [comment]
@eknowles would you like to submit this enhancement as a pull request, or should I just go ahead and do it?

**Comment by eknowles** [comment]
I'll do it :)

**Comment by Starefossen** [comment]
Grea, thanks :thumbsup:
