### ISSUE TITLE
Using $gt and $lt together

### ISSUE THREAD

**Issue by leobudima** [Turistforeningen/node-mongo-querystring#20]
Hi, 

thanks a lot for your effort on this library - extremely useful!

I'm having a problem, though, when using it to parse query params sent to a hapijs server and trying to specify a range of values for a parameter, such as:

`url?count=>10&count=<100`

parsed query comes out as:

`count: { '$in': [ '>10', '<100' ] } }`

The expected result would, naturally, be:

`count: {$gt: 10, $lt: 100}`

Do you have any suggestions on how to work around this, or is this something you would consider supporting? 

Thanks!

**Comment by Starefossen** [comment]
You suggestion has been implemented in `mongo-querystring@3.0.0`. Check it out :D

**Comment by leobudima** [comment]
Thanks so much, made my day! :) All the best!
