### ISSUE TITLE
Not and return

### ISSUE THREAD

**Issue by simon-p-r** [Turistforeningen/node-mongo-querystring#22]
Firstly thanks for this great library!

However the only operators I think are missing are the ability to control was it returned, I use the syntax "not" to exclude or "return" to include what fields are returned within document from mongo,

**Comment by Starefossen** [comment]
Hi @simon-p-r and thanks for the kind words!

Just to make sure I get what you are talking about; [projection](https://docs.mongodb.org/manual/tutorial/project-fields-from-query-results/) right?

```
>db.mycol.find({},{"title":1,_id:0})

{"title":"MongoDB Overview"}
{"title":"NoSQL Overview"}
{"title":"Tutorials Point Overview"}
```

I am not entirely convinced this is something the `mongo-querystring` library should do. In any case, this is how I would suggest this feature could look like on the URL query parameter:

```
?fields=field1&fields=field2&fields=!field3
```

This should evaluate to the following projection:

```json
{
  "field1": 1,
  "field2": 1,
  "field3": 0
}
```

**Comment by simon-p-r** [comment]
Yes projection,  the only problem is this module won't return this as a separate object.  I will close as I have now found [this](https://github.com/pbatey/query-to-mongo) module which handles this so will close this issue.
