### ISSUE TITLE
Custom array query

### ISSUE THREAD

**Issue by alexborisov** [Turistforeningen/node-mongo-querystring#40]
I want to create a custom query for an array. This is my structure:

```
{
  _id: 1234,
  assigned: {
    users: [{
      _id: 1111
    }]
  }
}
```

I expect that for this query

`?assigned[]=1111&assigned[]=2222`

I would write a function

```
function assigned(query, input) { // where input is [1111,2222]
  query['assigned.users._id'] = { $in: input }
}
```

**Comment by Starefossen** [comment]
Hi @alexborisov and thanks for using this library and submitting such a detailed ticket 😄 

I have found, and fixed, two unrelated errors which would have prevented this kind of custom query from work correctly. I have also added a test for this to prevent regressions. With the new version `4.0.1` this custom function should work:

```js
var qs = new MongoQS({
  custom: {
    assigned: function(query, input) {
      // make sure we handle normal strings (?assigned=1111)
      if (typeof input === 'string') {
        input = input.split(',');
      }

      query['assigned.users._id'] = {
        $in: inputValue.map(id => parseInt(id, 10))
      };
    }
  }
});
```

**Comment by alexborisov** [comment]
thank you! 👍
