### ISSUE TITLE
near query parameters

### ISSUE THREAD

**Issue by joshkopecek** [Turistforeningen/node-mongo-querystring#47]
When querying near leaving out the $minDistance parameters it fails.
`near=12.1234,13.1345,2000`
also when using a float for the $maxDistance it fails for me
`near=12.1234,13.1345,2000.1,0`

**Comment by Starefossen** [comment]
Thanks for the bug-report @joshkopecek. I have confirmed the bugs and I am working on a fix.

**Comment by Starefossen** [comment]
Both bugs are fixed in v4.0.2. Thanks for reporting @joshkopecek!
