### ISSUE TITLE
'[]' stripped from key names, array Regex fails, breaking $in & $nin

### ISSUE THREAD

**Issue by brianjd** [Turistforeningen/node-mongo-querystring#6]
As the title states, currently with in an Express environment (using qs as a query parser), the trailing brackets are being stripped from the key names.  This causes the regex to fail, as it is looking for `foo[]` and receiving `foo` instead.  So both $in and $nin are currently broken.

**Comment by Starefossen** [comment]
Thanks for the heads up @brianjd, really appreciate it!
