### ISSUE TITLE
Parsing String 'null'

### ISSUE THREAD

**Issue by JianChuanting** [Turistforeningen/node-mongo-querystring#61]
How to parse key=null?
Want to get null not 'null'.

**Comment by Starefossen** [comment]
Currently not possible, but pull request are welcome and you also become a collaborator member of the project if you contribute 👍

**Comment by Starefossen** [comment]
It is possible with a custom function: 

var qs = new MongoQS({
  custom: {
   myParam: function(query, input) {
      query.myParam = input === 'null' ? null : input;
    }
  }
});

**Comment by JianChuanting** [comment]
ok, thx!
