### ISSUE TITLE
Is there a way to query by ObjectID?

### ISSUE THREAD

**Issue by mhirsch** [Turistforeningen/node-mongo-querystring#64]
The node mongo driver supports querying by [ObjectID](https://mongodb.github.io/node-mongodb-native/api-bson-generated/objectid.html). Is there a way to do this using mongo-querystring? If not, would this be hard to implement?

**Comment by Starefossen** [comment]
You can make a custom query function for that:

```js
var qs = new MongoQS({
  custom: {
    my_id_field: function(query, input) {
      query.my_id_field = new ObjectId(input.my_id_field);
    }
  }
});
```

**Comment by mhirsch** [comment]
Thanks! That's perfect.
